USE [master]
GO

/****** Object:  Database [TelerikAcademy]    Script Date: 10/21/2013 19:13:50 PM ******/
CREATE DATABASE [TelerikAcademy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TelerikAcademy-Database', FILENAME = N'C:\Users\Stefan\Google Drive\Telerik Academy\Other\DataBases\TelerikAcademy-Database\TelerikAcademy-Database.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TelerikAcademy-Database_log', FILENAME = N'C:\Users\Stefan\Google Drive\Telerik Academy\Other\DataBases\TelerikAcademy-Database\TelerikAcademy-Database_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TelerikAcademy] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TelerikAcademy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TelerikAcademy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TelerikAcademy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TelerikAcademy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TelerikAcademy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TelerikAcademy] SET ARITHABORT OFF 
GO

ALTER DATABASE [TelerikAcademy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TelerikAcademy] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TelerikAcademy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TelerikAcademy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TelerikAcademy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TelerikAcademy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TelerikAcademy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TelerikAcademy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TelerikAcademy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TelerikAcademy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TelerikAcademy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TelerikAcademy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TelerikAcademy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TelerikAcademy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TelerikAcademy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TelerikAcademy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TelerikAcademy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TelerikAcademy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TelerikAcademy] SET RECOVERY FULL 
GO

ALTER DATABASE [TelerikAcademy] SET  MULTI_USER 
GO

ALTER DATABASE [TelerikAcademy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TelerikAcademy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TelerikAcademy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TelerikAcademy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TelerikAcademy] SET  READ_WRITE 
GO

